version: '3'
services:
    Cryptocop.Software.API:
        build: /Cryptocop.Software.API
        container_name: Cryptocop.Software.API
        ports:
            - "80:3000"
        networks:
            - "Cryptocop-network"
    cryptocop-db:
        image: mongo
        container_name: cryptocop-db
        networks:
            - "Cryptocop-network"
networks:
    Cryptocop-network:
        driver: bridge